version: '3.8'

services:
  app:
    container_name: climate-control
    image: magnussommarsjo/climate-control:latest
    working_dir: /app
    environment:
      MQTT_HOST: ${MQTT_HOST}
      STRATEGY_INFLUENCE: ${STRATEGY_INFLUENCE}
      STRATEGY_PERIOD: ${STRATEGY_PERIOD}

    restart: unless-stopped


