version: '3.8'

services:
  app:
    image: magnussommarsjo/climate-control:latest
    ports:
      - 8080:80
    working_dir: /climate_control
    environment:
      TZ: Europe/Stockholm
      HOST: "0.0.0.0"
      PORT: 80
      H60_ADDRESS: ${H60_ADDRESS}

    restart: unless-stopped
