version: '3.8'

services:
  app:
    build: .
    ports:
      - 8080:80
    working_dir: /climate_control
    environment:
      HOST: "0.0.0.0"
      PORT: 80
      TZ: Europe/Stockholm
      INFLUXDB_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    volumes:
      - app-data:/climate_control/data/
    depends_on: 
      - "influxdb2"
  influxdb2:
    image: influxdb:2.4
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_ORG: climate-control
      DOCKER_INFLUXDB_INIT_BUCKET: climate-control
      # Add below to an .env file or directly in shell env variables
      DOCKER_INFLUXDB_INIT_USERNAME: ${DOCKER_INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    volumes:
      - influxdb2:/var/lib/influxdb2


volumes:
  app-data:
  influxdb2:
